[build-system]
requires = ["maturin>=1.12,<2.0"]
build-backend = "maturin"

[project]
name = "rpgp-py"
description = "Python binding for rPGP, a Rust implementation of OpenPGP according to RFC 9580"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
dynamic = ["version"]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]

[project.urls]
repository = "https://github.com/xelandernt/rpgp-py"


[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.2",
    "pytest-cov>=7.1.0",
    "prek>=0.3.8",
    "maturin>=1.12.6",
    "pyrefly>=0.60.0",
]

[tool.maturin]
python-source = "src"
module-name = "openpgp._openpgp"
features = ["extension-module"]


[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--ignore=.tox/",
    "--ignore=tmp/"
]
pythonpath=["src", "tests"]


[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4
extend-include = ["*.pyi"]

target-version = "py310"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "PYI"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/openpgp"]

[tool.pyrefly]
project-includes = [
    "src",
    "tests",
]
search-path = [
    "src",
    "tests",
]
python-version = "3.10"
