from typing import Dict, List, Literal, Optional, Tuple, TypeAlias

Headers: TypeAlias = Dict[str, List[str]]
SymmetricAlgorithmName: TypeAlias = Literal["aes128", "aes192", "aes256"]
AeadAlgorithmName: TypeAlias = Literal["eax", "ocb", "gcm"]
CompressionAlgorithmName: TypeAlias = Literal["zip", "zlib", "bzip2"]
EncryptionVersionName: TypeAlias = Literal["seipd-v1", "seipd-v2"]
HashAlgorithmName: TypeAlias = Literal[
    "sha1", "sha224", "sha256", "sha384", "sha512", "sha3-256", "sha3-512"
]
StringToKeyKindName: TypeAlias = Literal[
    "simple", "salted", "reserved", "iterated-salted", "argon2", "private", "other"
]
S2kUsageName: TypeAlias = Literal[
    "unprotected", "legacy-cfb", "aead", "cfb", "malleable-cfb"
]
CurveName: TypeAlias = Literal[
    "curve25519",
    "p256",
    "p384",
    "p521",
    "brainpoolp256r1",
    "brainpoolp384r1",
    "brainpoolp512r1",
    "secp256k1",
]
EccCurveName: TypeAlias = Literal[
    "curve25519",
    "ed25519",
    "p256",
    "p384",
    "p521",
    "brainpoolp256r1",
    "brainpoolp384r1",
    "brainpoolp512r1",
    "secp256k1",
]
DsaKeySizeBits: TypeAlias = Literal[1024, 2048, 3072]
KeyVersionNumber: TypeAlias = Literal[4, 6]
AeadPreference: TypeAlias = Tuple[SymmetricAlgorithmName, AeadAlgorithmName]
PacketHeaderVersionName: TypeAlias = Literal["old", "new"]
PublicKeyAlgorithmName: TypeAlias = Literal[
    "rsa",
    "rsa-encrypt",
    "rsa-sign",
    "elgamal-encrypt",
    "dsa",
    "ecdh",
    "ecdsa",
    "elgamal",
    "diffie-hellman",
    "eddsa-legacy",
    "x25519",
    "x448",
    "ed25519",
    "ed448",
    "private-100",
    "private-101",
    "private-102",
    "private-103",
    "private-104",
    "private-105",
    "private-106",
    "private-107",
    "private-108",
    "private-109",
    "private-110",
    "unknown",
]
PublicParamsKindName: TypeAlias = Literal[
    "rsa",
    "dsa",
    "ecdsa",
    "ecdh",
    "elgamal",
    "eddsa-legacy",
    "ed25519",
    "x25519",
    "x448",
    "ed448",
    "unknown",
]

class PacketHeaderVersion:
    @staticmethod
    def old() -> PacketHeaderVersion: ...
    @staticmethod
    def new() -> PacketHeaderVersion: ...
    @property
    def name(self) -> PacketHeaderVersionName: ...

class EncryptionCaps:
    @staticmethod
    def none() -> EncryptionCaps: ...
    @staticmethod
    def communication() -> EncryptionCaps: ...
    @staticmethod
    def storage() -> EncryptionCaps: ...
    @staticmethod
    def all() -> EncryptionCaps: ...

class KeyType:
    @staticmethod
    def rsa(bits: int) -> KeyType: ...
    @staticmethod
    def dsa(bits: DsaKeySizeBits) -> KeyType: ...
    @staticmethod
    def ed25519_legacy() -> KeyType: ...
    @staticmethod
    def ed25519() -> KeyType: ...
    @staticmethod
    def ed448() -> KeyType: ...
    @staticmethod
    def ecdsa(curve: CurveName) -> KeyType: ...
    @staticmethod
    def ecdh(curve: CurveName) -> KeyType: ...
    @staticmethod
    def x25519() -> KeyType: ...
    @staticmethod
    def x448() -> KeyType: ...
    def can_sign(self) -> bool: ...
    def can_encrypt(self) -> bool: ...

class StringToKey:
    @staticmethod
    def iterated(
        hash_algorithm: HashAlgorithmName,
        count: int,
        salt: Optional[bytes] = None,
    ) -> StringToKey: ...
    @staticmethod
    def argon2(
        passes: int,
        parallelism: int,
        memory_exponent: int,
        salt: Optional[bytes] = None,
    ) -> StringToKey: ...
    @property
    def type_id(self) -> int: ...
    @property
    def kind(self) -> StringToKeyKindName: ...
    @property
    def hash_algorithm(self) -> Optional[HashAlgorithmName]: ...
    @property
    def salt(self) -> Optional[bytes]: ...
    @property
    def count(self) -> Optional[int]: ...
    @property
    def passes(self) -> Optional[int]: ...
    @property
    def parallelism(self) -> Optional[int]: ...
    @property
    def memory_exponent(self) -> Optional[int]: ...

class S2kParams:
    @staticmethod
    def cfb(
        symmetric_algorithm: SymmetricAlgorithmName,
        string_to_key: StringToKey,
        iv: Optional[bytes] = None,
    ) -> S2kParams: ...
    @staticmethod
    def aead(
        symmetric_algorithm: SymmetricAlgorithmName,
        aead_algorithm: AeadAlgorithmName,
        string_to_key: StringToKey,
        nonce: Optional[bytes] = None,
    ) -> S2kParams: ...
    @property
    def usage_id(self) -> int: ...
    @property
    def usage(self) -> S2kUsageName: ...
    @property
    def symmetric_algorithm(self) -> Optional[SymmetricAlgorithmName]: ...
    @property
    def aead_algorithm(self) -> Optional[AeadAlgorithmName]: ...
    @property
    def string_to_key(self) -> Optional[StringToKey]: ...
    @property
    def iv(self) -> Optional[bytes]: ...
    @property
    def nonce(self) -> Optional[bytes]: ...

class SubkeyParams: ...

class SubkeyParamsBuilder:
    def __init__(self) -> None: ...
    def version(self, value: KeyVersionNumber) -> SubkeyParamsBuilder: ...
    def key_type(self, value: KeyType) -> SubkeyParamsBuilder: ...
    def can_sign(self, value: bool) -> SubkeyParamsBuilder: ...
    def can_encrypt(self, value: EncryptionCaps) -> SubkeyParamsBuilder: ...
    def can_authenticate(self, value: bool) -> SubkeyParamsBuilder: ...
    def created_at(self, value: int) -> SubkeyParamsBuilder: ...
    def packet_version(self, value: PacketHeaderVersion) -> SubkeyParamsBuilder: ...
    def passphrase(self, value: Optional[str]) -> SubkeyParamsBuilder: ...
    def s2k(self, value: S2kParams) -> SubkeyParamsBuilder: ...
    def build(self) -> SubkeyParams: ...

class SecretKeyParams:
    def generate(self) -> SecretKey: ...

class UserAttribute:
    @staticmethod
    def image_jpeg(data: bytes) -> UserAttribute: ...
    @property
    def kind(self) -> Literal["image", "unknown"]: ...
    @property
    def data(self) -> bytes: ...
    @property
    def image_header_version(self) -> Optional[int]: ...
    @property
    def image_format(self) -> Optional[str]: ...

class SecretKeyParamsBuilder:
    def __init__(self) -> None: ...
    def version(self, value: KeyVersionNumber) -> SecretKeyParamsBuilder: ...
    def key_type(self, value: KeyType) -> SecretKeyParamsBuilder: ...
    def can_sign(self, value: bool) -> SecretKeyParamsBuilder: ...
    def can_certify(self, value: bool) -> SecretKeyParamsBuilder: ...
    def can_encrypt(self, value: EncryptionCaps) -> SecretKeyParamsBuilder: ...
    def can_authenticate(self, value: bool) -> SecretKeyParamsBuilder: ...
    def created_at(self, value: int) -> SecretKeyParamsBuilder: ...
    def packet_version(self, value: PacketHeaderVersion) -> SecretKeyParamsBuilder: ...
    def feature_seipd_v1(self, value: bool) -> SecretKeyParamsBuilder: ...
    def feature_seipd_v2(self, value: bool) -> SecretKeyParamsBuilder: ...
    def preferred_symmetric_algorithms(
        self, values: List[SymmetricAlgorithmName]
    ) -> SecretKeyParamsBuilder: ...
    def preferred_hash_algorithms(
        self, values: List[HashAlgorithmName]
    ) -> SecretKeyParamsBuilder: ...
    def preferred_compression_algorithms(
        self, values: List[CompressionAlgorithmName]
    ) -> SecretKeyParamsBuilder: ...
    def preferred_aead_algorithms(
        self, values: List[AeadPreference]
    ) -> SecretKeyParamsBuilder: ...
    def passphrase(self, value: Optional[str]) -> SecretKeyParamsBuilder: ...
    def s2k(self, value: S2kParams) -> SecretKeyParamsBuilder: ...
    def primary_user_id(self, value: str) -> SecretKeyParamsBuilder: ...
    def user_id(self, value: str) -> SecretKeyParamsBuilder: ...
    def user_ids(self, values: List[str]) -> SecretKeyParamsBuilder: ...
    def user_attribute(self, value: UserAttribute) -> SecretKeyParamsBuilder: ...
    def user_attributes(
        self, values: List[UserAttribute]
    ) -> SecretKeyParamsBuilder: ...
    def subkey(self, value: SubkeyParams) -> SecretKeyParamsBuilder: ...
    def build(self) -> SecretKeyParams: ...
    def generate(self) -> SecretKey: ...

class PublicParamsInfo:
    @property
    def kind(self) -> PublicParamsKindName: ...
    @property
    def curve(self) -> Optional[EccCurveName]: ...
    @property
    def curve_oid(self) -> Optional[str]: ...
    @property
    def curve_alias(self) -> Optional[str]: ...
    @property
    def curve_bits(self) -> Optional[int]: ...
    @property
    def dsa_bits(self) -> Optional[int]: ...
    @property
    def rsa_bits(self) -> Optional[int]: ...
    @property
    def secret_key_length(self) -> Optional[int]: ...
    @property
    def is_supported(self) -> Optional[bool]: ...
    @property
    def kdf_hash_algorithm(self) -> Optional[HashAlgorithmName]: ...
    @property
    def kdf_symmetric_algorithm(self) -> Optional[SymmetricAlgorithmName]: ...
    @property
    def kdf_type(self) -> Optional[str]: ...

class PublicKey:
    @staticmethod
    def from_armor(data: str) -> Tuple[PublicKey, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> PublicKey: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def created_at(self) -> int: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def public_params(self) -> PublicParamsInfo: ...
    @property
    def packet_version(self) -> PacketHeaderVersion: ...
    @property
    def public_subkey_count(self) -> int: ...
    @property
    def user_ids(self) -> List[str]: ...
    def direct_signature_infos(self) -> List[SignatureInfo]: ...
    def revocation_signature_infos(self) -> List[SignatureInfo]: ...
    def user_bindings(self) -> List[UserBindingInfo]: ...
    def user_attribute_bindings(self) -> List[UserAttributeBindingInfo]: ...
    def subkey_bindings(self) -> List[SubkeyBindingInfo]: ...
    def verify_bindings(self) -> None: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...

class SecretKey:
    @staticmethod
    def from_armor(data: str) -> Tuple[SecretKey, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> SecretKey: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def created_at(self) -> int: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def public_params(self) -> PublicParamsInfo: ...
    @property
    def packet_version(self) -> PacketHeaderVersion: ...
    @property
    def public_subkey_count(self) -> int: ...
    @property
    def secret_subkey_count(self) -> int: ...
    @property
    def user_ids(self) -> List[str]: ...
    def direct_signature_infos(self) -> List[SignatureInfo]: ...
    def revocation_signature_infos(self) -> List[SignatureInfo]: ...
    def user_bindings(self) -> List[UserBindingInfo]: ...
    def user_attribute_bindings(self) -> List[UserAttributeBindingInfo]: ...
    def subkey_bindings(self) -> List[SubkeyBindingInfo]: ...
    def primary_secret_s2k(self) -> S2kParams: ...
    def secret_subkey_s2ks(self) -> List[S2kParams]: ...
    def verify_bindings(self) -> None: ...
    def to_public_key(self) -> PublicKey: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...

class KeyFlagsInfo:
    @property
    def certify(self) -> bool: ...
    @property
    def sign(self) -> bool: ...
    @property
    def encrypt_communications(self) -> bool: ...
    @property
    def encrypt_storage(self) -> bool: ...
    @property
    def authenticate(self) -> bool: ...
    @property
    def shared(self) -> bool: ...
    @property
    def draft_decrypt_forwarded(self) -> bool: ...
    @property
    def group(self) -> bool: ...
    @property
    def adsk(self) -> bool: ...
    @property
    def timestamping(self) -> bool: ...

class FeaturesInfo:
    @property
    def seipd_v1(self) -> bool: ...
    @property
    def seipd_v2(self) -> bool: ...

class UserAttributeBindingInfo:
    @property
    def user_attribute(self) -> UserAttribute: ...
    @property
    def signatures(self) -> List[SignatureInfo]: ...

class SubkeyBindingInfo:
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def created_at(self) -> int: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def public_params(self) -> PublicParamsInfo: ...
    @property
    def packet_version(self) -> PacketHeaderVersion: ...
    @property
    def signatures(self) -> List[SignatureInfo]: ...

class UserBindingInfo:
    @property
    def user_id(self) -> str: ...
    @property
    def is_primary(self) -> bool: ...
    @property
    def signatures(self) -> List[SignatureInfo]: ...

class SignatureNotationInfo:
    @property
    def human_readable(self) -> bool: ...
    @property
    def name(self) -> bytes: ...
    @property
    def value(self) -> bytes: ...

class RevocationKeyInfo:
    @property
    def class_id(self) -> int: ...
    @property
    def class_name(self) -> Literal["default", "sensitive"]: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def fingerprint(self) -> bytes: ...

class SignatureInfo:
    @property
    def version(self) -> int: ...
    @property
    def signature_type(self) -> Optional[str]: ...
    @property
    def hash_algorithm(self) -> Optional[str]: ...
    @property
    def public_key_algorithm(self) -> Optional[PublicKeyAlgorithmName]: ...
    @property
    def issuer_key_ids(self) -> List[str]: ...
    @property
    def issuer_fingerprints(self) -> List[str]: ...
    @property
    def creation_time(self) -> Optional[int]: ...
    @property
    def key_expiration_seconds(self) -> Optional[int]: ...
    @property
    def signature_expiration_seconds(self) -> Optional[int]: ...
    @property
    def revocation_reason_code(self) -> Optional[int]: ...
    @property
    def revocation_reason(self) -> Optional[str]: ...
    @property
    def signer_user_id(self) -> Optional[str]: ...
    @property
    def signed_hash_value(self) -> Optional[bytes]: ...
    @property
    def salt(self) -> Optional[bytes]: ...
    @property
    def preferred_symmetric_algorithms(self) -> List[str]: ...
    @property
    def preferred_hash_algorithms(self) -> List[str]: ...
    @property
    def preferred_compression_algorithms(self) -> List[str]: ...
    @property
    def preferred_aead_algorithms(self) -> List[Tuple[str, str]]: ...
    @property
    def preferred_key_server(self) -> Optional[str]: ...
    @property
    def notations(self) -> List[SignatureNotationInfo]: ...
    @property
    def revocation_key(self) -> Optional[RevocationKeyInfo]: ...
    @property
    def policy_uri(self) -> Optional[str]: ...
    @property
    def is_revocable(self) -> bool: ...
    @property
    def exportable_certification(self) -> bool: ...
    @property
    def key_flags(self) -> KeyFlagsInfo: ...
    @property
    def features(self) -> Optional[FeaturesInfo]: ...
    @property
    def embedded_signature(self) -> Optional[SignatureInfo]: ...
    @property
    def is_one_pass(self) -> bool: ...

class PublicKeyEncryptedSessionKeyPacket:
    @property
    def version(self) -> int: ...
    @property
    def public_key_algorithm(self) -> Optional[PublicKeyAlgorithmName]: ...
    @property
    def recipient_key_id(self) -> Optional[str]: ...
    @property
    def recipient_fingerprint(self) -> Optional[str]: ...
    @property
    def recipient_is_anonymous(self) -> bool: ...
    def values_bytes(self) -> Optional[bytes]: ...
    def to_bytes(self) -> bytes: ...

class SymKeyEncryptedSessionKeyPacket:
    @property
    def version(self) -> int: ...
    @property
    def symmetric_algorithm(self) -> Optional[SymmetricAlgorithmName]: ...
    @property
    def aead_algorithm(self) -> Optional[AeadAlgorithmName]: ...
    @property
    def string_to_key(self) -> Optional[StringToKey]: ...
    @property
    def encrypted_key(self) -> Optional[bytes]: ...
    @property
    def aead_iv(self) -> Optional[bytes]: ...
    @property
    def is_supported(self) -> bool: ...
    def to_bytes(self) -> bytes: ...

class EncryptedDataPacket:
    @property
    def kind(self) -> Literal["sed", "seipd-v1", "seipd-v2", "gnupg-aead"]: ...
    @property
    def version(self) -> Optional[int]: ...
    @property
    def symmetric_algorithm(self) -> Optional[SymmetricAlgorithmName]: ...
    @property
    def aead_algorithm(self) -> Optional[AeadAlgorithmName]: ...
    @property
    def chunk_size(self) -> Optional[int]: ...
    @property
    def salt(self) -> Optional[bytes]: ...
    @property
    def iv(self) -> Optional[bytes]: ...
    def data(self) -> bytes: ...
    def to_bytes(self) -> bytes: ...

class Message:
    @staticmethod
    def from_armor(data: str) -> Tuple[Message, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> Message: ...
    def to_bytes(self) -> bytes: ...
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def headers(self) -> Optional[Headers]: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def is_compressed(self) -> bool: ...
    @property
    def is_literal(self) -> bool: ...
    def payload_bytes(self) -> bytes: ...
    def payload_text(self) -> str: ...
    def literal_mode(self) -> Optional[str]: ...
    def literal_filename(self) -> Optional[bytes]: ...
    def signature_count(self) -> int: ...
    def one_pass_signature_count(self) -> int: ...
    def regular_signature_count(self) -> int: ...
    def signature_infos(self) -> List[SignatureInfo]: ...
    def public_key_encrypted_session_key_packets(
        self,
    ) -> List[PublicKeyEncryptedSessionKeyPacket]: ...
    def symmetric_key_encrypted_session_key_packets(
        self,
    ) -> List[SymKeyEncryptedSessionKeyPacket]: ...
    def encrypted_data_packet(self) -> EncryptedDataPacket: ...
    def verify_signature(self, key: PublicKey, index: int = 0) -> SignatureInfo: ...
    def verify(self, key: PublicKey, index: int = 0) -> None: ...
    def decrypt(
        self, key: SecretKey, password: Optional[str] = None
    ) -> DecryptedMessage: ...
    def decrypt_with_password(self, password: str) -> DecryptedMessage: ...
    def decrypt_with_session_key(
        self,
        session_key: bytes,
        symmetric_algorithm: Optional[SymmetricAlgorithmName] = None,
    ) -> DecryptedMessage: ...

class DecryptedMessage:
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def is_compressed(self) -> bool: ...
    @property
    def is_literal(self) -> bool: ...
    def payload_bytes(self) -> bytes: ...
    def payload_text(self) -> str: ...
    def literal_mode(self) -> Optional[str]: ...
    def literal_filename(self) -> Optional[bytes]: ...
    def signature_count(self) -> int: ...
    def one_pass_signature_count(self) -> int: ...
    def regular_signature_count(self) -> int: ...
    def signature_infos(self) -> List[SignatureInfo]: ...
    def verify_signature(self, key: PublicKey, index: int = 0) -> SignatureInfo: ...
    def verify(self, key: PublicKey, index: int = 0) -> None: ...

class DetachedSignature:
    @staticmethod
    def from_armor(data: str) -> Tuple[DetachedSignature, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> DetachedSignature: ...
    @staticmethod
    def sign_binary(
        data: bytes,
        key: SecretKey,
        password: Optional[str] = None,
        hash_algorithm: HashAlgorithmName = "sha256",
    ) -> DetachedSignature: ...
    @staticmethod
    def sign_text(
        text: str,
        key: SecretKey,
        password: Optional[str] = None,
        hash_algorithm: HashAlgorithmName = "sha256",
    ) -> DetachedSignature: ...
    def signature_info(self) -> SignatureInfo: ...
    def verify(self, key: PublicKey, data: bytes) -> None: ...
    def verify_signature(self, key: PublicKey, data: bytes) -> SignatureInfo: ...
    def verify_text(self, key: PublicKey, text: str) -> None: ...
    def verify_text_signature(self, key: PublicKey, text: str) -> SignatureInfo: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...

class CleartextSignedMessage:
    @staticmethod
    def from_armor(data: str) -> Tuple[CleartextSignedMessage, Headers]: ...
    @staticmethod
    def sign(
        text: str,
        key: SecretKey,
        password: Optional[str] = None,
        hash_algorithm: HashAlgorithmName = "sha256",
    ) -> CleartextSignedMessage: ...
    @property
    def text(self) -> str: ...
    def signed_text(self) -> str: ...
    def signature_count(self) -> int: ...
    def signature_infos(self) -> List[SignatureInfo]: ...
    def verify_signature(
        self, key: PublicKey, index: Optional[int] = None
    ) -> SignatureInfo: ...
    def verify(self, key: PublicKey, index: Optional[int] = None) -> None: ...
    def to_armored(self) -> str: ...

class MessageInfo:
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def headers(self) -> Optional[Headers]: ...

def inspect_message(data: str) -> MessageInfo: ...
def inspect_message_bytes(data: bytes) -> MessageInfo: ...
def sign_message(
    data: bytes,
    signer: SecretKey,
    password: Optional[str] = None,
    file_name: str = "",
    hash_algorithm: HashAlgorithmName = "sha256",
) -> str: ...
def sign_message_many(
    data: bytes,
    signers: List[SecretKey],
    passwords: Optional[List[Optional[str]]] = None,
    file_name: str = "",
    hash_algorithm: HashAlgorithmName = "sha256",
) -> str: ...
def sign_cleartext_message(
    text: str,
    signer: SecretKey,
    password: Optional[str] = None,
    hash_algorithm: HashAlgorithmName = "sha256",
) -> str: ...
def sign_cleartext_message_many(
    text: str,
    signers: List[SecretKey],
    passwords: Optional[List[Optional[str]]] = None,
    hash_algorithm: HashAlgorithmName = "sha256",
) -> str: ...
def encrypt_session_key_to_recipient(
    session_key: bytes,
    recipient: PublicKey,
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    anonymous_recipient: bool = False,
) -> PublicKeyEncryptedSessionKeyPacket: ...
def encrypt_session_key_with_password(
    session_key: bytes,
    password: str,
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
) -> SymKeyEncryptedSessionKeyPacket: ...
def encrypt_message_to_recipient_bytes(
    data: bytes,
    recipient: PublicKey,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
    anonymous_recipient: bool = False,
) -> bytes: ...
def encrypt_message_to_recipients_bytes(
    data: bytes,
    recipients: List[PublicKey],
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
    anonymous_recipient: bool = False,
) -> bytes: ...
def encrypt_message_to_recipient(
    data: bytes,
    recipient: PublicKey,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
    anonymous_recipient: bool = False,
) -> str: ...
def encrypt_message_to_recipients(
    data: bytes,
    recipients: List[PublicKey],
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
    anonymous_recipient: bool = False,
) -> str: ...
def encrypt_message_with_password_bytes(
    data: bytes,
    password: str,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
) -> bytes: ...
def encrypt_message_with_password(
    data: bytes,
    password: str,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
) -> str: ...
