from os import PathLike
from typing import (
    BinaryIO,
    Dict,
    List,
    Literal,
    Optional,
    Protocol,
    TextIO,
    Tuple,
    TypeAlias,
    Union,
)

FilePath: TypeAlias = Union[str, PathLike[str]]
Headers: TypeAlias = Dict[str, List[str]]
SymmetricAlgorithmName: TypeAlias = Literal["aes128", "aes192", "aes256"]
AeadAlgorithmName: TypeAlias = Literal["eax", "ocb", "gcm"]
CompressionAlgorithmName: TypeAlias = Literal["zip", "zlib", "bzip2"]
EncryptionVersionName: TypeAlias = Literal["seipd-v1", "seipd-v2"]
HashAlgorithmName: TypeAlias = Literal[
    "sha1", "sha224", "sha256", "sha384", "sha512", "sha3-256", "sha3-512"
]
StringToKeyKindName: TypeAlias = Literal[
    "simple", "salted", "reserved", "iterated-salted", "argon2", "private", "other"
]
S2kUsageName: TypeAlias = Literal[
    "unprotected", "legacy-cfb", "aead", "cfb", "malleable-cfb"
]
CurveName: TypeAlias = Literal[
    "curve25519",
    "p256",
    "p384",
    "p521",
    "brainpoolp256r1",
    "brainpoolp384r1",
    "brainpoolp512r1",
    "secp256k1",
]
EccCurveName: TypeAlias = Literal[
    "curve25519",
    "ed25519",
    "p256",
    "p384",
    "p521",
    "brainpoolp256r1",
    "brainpoolp384r1",
    "brainpoolp512r1",
    "secp256k1",
]
DsaKeySizeBits: TypeAlias = Literal[1024, 2048, 3072]
KeyVersionNumber: TypeAlias = Literal[4, 6]
AeadPreference: TypeAlias = Tuple[SymmetricAlgorithmName, AeadAlgorithmName]
PacketHeaderVersionName: TypeAlias = Literal["old", "new"]
LiteralDataModeName: TypeAlias = Literal["binary", "utf8"]
PublicKeyAlgorithmName: TypeAlias = Literal[
    "rsa",
    "rsa-encrypt",
    "rsa-sign",
    "elgamal-encrypt",
    "dsa",
    "ecdh",
    "ecdsa",
    "elgamal",
    "diffie-hellman",
    "eddsa-legacy",
    "x25519",
    "x448",
    "ed25519",
    "ed448",
    "private-100",
    "private-101",
    "private-102",
    "private-103",
    "private-104",
    "private-105",
    "private-106",
    "private-107",
    "private-108",
    "private-109",
    "private-110",
    "unknown",
]
PublicParamsKindName: TypeAlias = Literal[
    "rsa",
    "dsa",
    "ecdsa",
    "ecdh",
    "elgamal",
    "eddsa-legacy",
    "ed25519",
    "x25519",
    "x448",
    "ed448",
    "unknown",
]
EncryptionRecipient: TypeAlias = Union[SignedPublicKey, SignedPublicSubKey]
SigningKey: TypeAlias = Union[SignedSecretKey, SignedSecretSubKey]

class CryptoRng(Protocol):
    def randbytes(self, n: int) -> bytes: ...

class PacketHeaderVersion:
    @staticmethod
    def old() -> PacketHeaderVersion: ...
    @staticmethod
    def new() -> PacketHeaderVersion: ...
    @property
    def name(self) -> PacketHeaderVersionName: ...

class ArmorOptions:
    def __init__(
        self, headers: Optional[Headers] = None, include_checksum: bool = True
    ) -> None: ...
    @property
    def headers(self) -> Optional[Headers]: ...
    @property
    def include_checksum(self) -> bool: ...

class EncryptionCaps:
    @staticmethod
    def none() -> EncryptionCaps: ...
    @staticmethod
    def communication() -> EncryptionCaps: ...
    @staticmethod
    def storage() -> EncryptionCaps: ...
    @staticmethod
    def all() -> EncryptionCaps: ...

class KeyType:
    @staticmethod
    def rsa(bits: int) -> KeyType: ...
    @staticmethod
    def dsa(bits: DsaKeySizeBits) -> KeyType: ...
    @staticmethod
    def ed25519_legacy() -> KeyType: ...
    @staticmethod
    def ed25519() -> KeyType: ...
    @staticmethod
    def ed448() -> KeyType: ...
    @staticmethod
    def ecdsa(curve: CurveName) -> KeyType: ...
    @staticmethod
    def ecdh(curve: CurveName) -> KeyType: ...
    @staticmethod
    def x25519() -> KeyType: ...
    @staticmethod
    def x448() -> KeyType: ...
    def can_sign(self) -> bool: ...
    def can_encrypt(self) -> bool: ...

class StringToKey:
    @staticmethod
    def iterated(
        hash_algorithm: HashAlgorithmName,
        count: int,
        salt: Optional[bytes] = None,
    ) -> StringToKey: ...
    @staticmethod
    def argon2(
        passes: int,
        parallelism: int,
        memory_exponent: int,
        salt: Optional[bytes] = None,
    ) -> StringToKey: ...
    @property
    def type_id(self) -> int: ...
    @property
    def kind(self) -> StringToKeyKindName: ...
    @property
    def hash_algorithm(self) -> Optional[HashAlgorithmName]: ...
    @property
    def salt(self) -> Optional[bytes]: ...
    @property
    def count(self) -> Optional[int]: ...
    @property
    def passes(self) -> Optional[int]: ...
    @property
    def parallelism(self) -> Optional[int]: ...
    @property
    def memory_exponent(self) -> Optional[int]: ...

class S2kParams:
    @staticmethod
    def cfb(
        symmetric_algorithm: SymmetricAlgorithmName,
        string_to_key: StringToKey,
        iv: Optional[bytes] = None,
    ) -> S2kParams: ...
    @staticmethod
    def aead(
        symmetric_algorithm: SymmetricAlgorithmName,
        aead_algorithm: AeadAlgorithmName,
        string_to_key: StringToKey,
        nonce: Optional[bytes] = None,
    ) -> S2kParams: ...
    @property
    def usage_id(self) -> int: ...
    @property
    def usage(self) -> S2kUsageName: ...
    @property
    def symmetric_algorithm(self) -> Optional[SymmetricAlgorithmName]: ...
    @property
    def aead_algorithm(self) -> Optional[AeadAlgorithmName]: ...
    @property
    def string_to_key(self) -> Optional[StringToKey]: ...
    @property
    def iv(self) -> Optional[bytes]: ...
    @property
    def nonce(self) -> Optional[bytes]: ...

class SubkeyParams: ...

class SubkeyParamsBuilder:
    def __init__(self) -> None: ...
    def version(self, value: KeyVersionNumber) -> SubkeyParamsBuilder: ...
    def key_type(self, value: KeyType) -> SubkeyParamsBuilder: ...
    def can_sign(self, value: bool) -> SubkeyParamsBuilder: ...
    def can_encrypt(self, value: EncryptionCaps) -> SubkeyParamsBuilder: ...
    def can_authenticate(self, value: bool) -> SubkeyParamsBuilder: ...
    def created_at(self, value: int) -> SubkeyParamsBuilder: ...
    def packet_version(self, value: PacketHeaderVersion) -> SubkeyParamsBuilder: ...
    def passphrase(self, value: Optional[str]) -> SubkeyParamsBuilder: ...
    def s2k(self, value: S2kParams) -> SubkeyParamsBuilder: ...
    def build(self) -> SubkeyParams: ...

class SecretKeyParams:
    def generate(self) -> SignedSecretKey: ...

class UserAttribute:
    @staticmethod
    def image_jpeg(data: bytes) -> UserAttribute: ...
    @property
    def kind(self) -> Literal["image", "unknown"]: ...
    @property
    def data(self) -> bytes: ...
    @property
    def image_header_version(self) -> Optional[int]: ...
    @property
    def image_format(self) -> Optional[str]: ...

class SecretKeyParamsBuilder:
    def __init__(self) -> None: ...
    def version(self, value: KeyVersionNumber) -> SecretKeyParamsBuilder: ...
    def key_type(self, value: KeyType) -> SecretKeyParamsBuilder: ...
    def can_sign(self, value: bool) -> SecretKeyParamsBuilder: ...
    def can_certify(self, value: bool) -> SecretKeyParamsBuilder: ...
    def can_encrypt(self, value: EncryptionCaps) -> SecretKeyParamsBuilder: ...
    def can_authenticate(self, value: bool) -> SecretKeyParamsBuilder: ...
    def created_at(self, value: int) -> SecretKeyParamsBuilder: ...
    def packet_version(self, value: PacketHeaderVersion) -> SecretKeyParamsBuilder: ...
    def feature_seipd_v1(self, value: bool) -> SecretKeyParamsBuilder: ...
    def feature_seipd_v2(self, value: bool) -> SecretKeyParamsBuilder: ...
    def preferred_symmetric_algorithms(
        self, values: List[SymmetricAlgorithmName]
    ) -> SecretKeyParamsBuilder: ...
    def preferred_hash_algorithms(
        self, values: List[HashAlgorithmName]
    ) -> SecretKeyParamsBuilder: ...
    def preferred_compression_algorithms(
        self, values: List[CompressionAlgorithmName]
    ) -> SecretKeyParamsBuilder: ...
    def preferred_aead_algorithms(
        self, values: List[AeadPreference]
    ) -> SecretKeyParamsBuilder: ...
    def passphrase(self, value: Optional[str]) -> SecretKeyParamsBuilder: ...
    def s2k(self, value: S2kParams) -> SecretKeyParamsBuilder: ...
    def primary_user_id(self, value: str) -> SecretKeyParamsBuilder: ...
    def user_id(self, value: str) -> SecretKeyParamsBuilder: ...
    def user_ids(self, values: List[str]) -> SecretKeyParamsBuilder: ...
    def user_attribute(self, value: UserAttribute) -> SecretKeyParamsBuilder: ...
    def user_attributes(
        self, values: List[UserAttribute]
    ) -> SecretKeyParamsBuilder: ...
    def subkey(self, value: SubkeyParams) -> SecretKeyParamsBuilder: ...
    def build(self) -> SecretKeyParams: ...
    def generate(self) -> SignedSecretKey: ...

class PublicParams:
    @property
    def kind(self) -> PublicParamsKindName: ...
    @property
    def curve(self) -> Optional[EccCurveName]: ...
    @property
    def curve_oid(self) -> Optional[str]: ...
    @property
    def curve_alias(self) -> Optional[str]: ...
    @property
    def curve_bits(self) -> Optional[int]: ...
    @property
    def dsa_bits(self) -> Optional[int]: ...
    @property
    def rsa_bits(self) -> Optional[int]: ...
    @property
    def secret_key_length(self) -> Optional[int]: ...
    @property
    def is_supported(self) -> Optional[bool]: ...
    @property
    def kdf_hash_algorithm(self) -> Optional[HashAlgorithmName]: ...
    @property
    def kdf_symmetric_algorithm(self) -> Optional[SymmetricAlgorithmName]: ...
    @property
    def kdf_type(self) -> Optional[str]: ...
    def to_bytes(self) -> bytes: ...

class RsaPublicKey:
    @property
    def n(self) -> bytes: ...
    @property
    def e(self) -> bytes: ...

class DsaPublicKey:
    @property
    def p(self) -> bytes: ...
    @property
    def q(self) -> bytes: ...
    @property
    def g(self) -> bytes: ...
    @property
    def y(self) -> bytes: ...

class RsaPublicParams(PublicParams):
    @property
    def key(self) -> RsaPublicKey: ...

class DsaPublicParams(PublicParams):
    @property
    def key(self) -> DsaPublicKey: ...

class EcdsaPublicParams(PublicParams):
    @property
    def key(self) -> Optional[bytes]: ...
    @property
    def opaque(self) -> Optional[bytes]: ...

class EcdhPublicParams(PublicParams):
    @property
    def p(self) -> Optional[bytes]: ...
    @property
    def opaque(self) -> Optional[bytes]: ...
    @property
    def hash(self) -> HashAlgorithmName: ...
    @property
    def alg_sym(self) -> SymmetricAlgorithmName: ...
    @property
    def ecdh_kdf_type(self) -> str: ...

class ElgamalPublicParams(PublicParams): ...

class EdDsaLegacyPublicParams(PublicParams):
    @property
    def key(self) -> Optional[bytes]: ...
    @property
    def opaque(self) -> Optional[bytes]: ...

class Ed25519PublicParams(PublicParams):
    @property
    def key(self) -> bytes: ...

class X25519PublicParams(PublicParams):
    @property
    def key(self) -> bytes: ...

class X448PublicParams(PublicParams):
    @property
    def key(self) -> bytes: ...

class Ed448PublicParams(PublicParams):
    @property
    def key(self) -> bytes: ...

class UnknownPublicParams(PublicParams):
    @property
    def data(self) -> bytes: ...

class PublicKey:
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def created_at(self) -> int: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def public_params(self) -> PublicParams: ...
    @property
    def packet_version(self) -> PacketHeaderVersion: ...

class PublicSubkey:
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def created_at(self) -> int: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def public_params(self) -> PublicParams: ...
    @property
    def packet_version(self) -> PacketHeaderVersion: ...

class SecretKey:
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def created_at(self) -> int: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def public_params(self) -> PublicParams: ...
    @property
    def packet_version(self) -> PacketHeaderVersion: ...
    @property
    def secret_s2k(self) -> S2kParams: ...

class SecretSubkey:
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def created_at(self) -> int: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def public_params(self) -> PublicParams: ...
    @property
    def packet_version(self) -> PacketHeaderVersion: ...
    @property
    def secret_s2k(self) -> S2kParams: ...

class Signature:
    def version(self) -> int: ...
    def typ(self) -> Optional[str]: ...
    def hash_alg(self) -> Optional[HashAlgorithmName]: ...
    def signed_hash_value(self) -> Optional[bytes]: ...
    def salt(self) -> Optional[bytes]: ...
    def key_expiration_time(self) -> Optional[int]: ...
    def signature_expiration_time(self) -> Optional[int]: ...
    def created(self) -> Optional[int]: ...
    def issuer_key_id(self) -> List[str]: ...
    def issuer_fingerprint(self) -> List[str]: ...
    def preferred_symmetric_algs(self) -> List[SymmetricAlgorithmName]: ...
    def preferred_aead_algs(self) -> List[AeadPreference]: ...
    def preferred_hash_algs(self) -> List[HashAlgorithmName]: ...
    def preferred_compression_algs(self) -> List[CompressionAlgorithmName]: ...
    def key_flags(self) -> KeyFlags: ...
    def features(self) -> Optional[Features]: ...
    def embedded_signature(self) -> Optional[Signature]: ...
    def preferred_key_server(self) -> Optional[str]: ...
    def notations(self) -> List[Notation]: ...
    def revocation_key(self) -> Optional[RevocationKey]: ...
    def signers_userid(self) -> Optional[str]: ...
    def policy_uri(self) -> Optional[str]: ...
    def is_revocable(self) -> bool: ...
    def exportable_certification(self) -> bool: ...
    def to_bytes(self) -> bytes: ...

class SignedUser:
    @property
    def id(self) -> str: ...
    @property
    def user_id(self) -> str: ...
    @property
    def signatures(self) -> List[Signature]: ...
    @property
    def is_primary(self) -> bool: ...

class SignedUserAttribute:
    @property
    def attr(self) -> UserAttribute: ...
    @property
    def user_attribute(self) -> UserAttribute: ...
    @property
    def signatures(self) -> List[Signature]: ...

class SignedKeyDetails:
    @property
    def revocation_signatures(self) -> List[Signature]: ...
    @property
    def direct_signatures(self) -> List[Signature]: ...
    @property
    def users(self) -> List[SignedUser]: ...
    @property
    def user_attributes(self) -> List[SignedUserAttribute]: ...

class SignedPublicSubKey:
    @property
    def key(self) -> PublicSubkey: ...
    @property
    def signatures(self) -> List[Signature]: ...

class SignedSecretSubKey:
    @property
    def key(self) -> SecretSubkey: ...
    @property
    def signatures(self) -> List[Signature]: ...
    def signed_public_key(self) -> SignedPublicSubKey: ...

class SignedPublicKey:
    @staticmethod
    def from_armor(data: str) -> Tuple[SignedPublicKey, Headers]: ...
    @staticmethod
    def from_armor_many(data: str) -> Tuple[List[SignedPublicKey], Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> SignedPublicKey: ...
    @staticmethod
    def from_bytes_many(data: bytes) -> List[SignedPublicKey]: ...
    @staticmethod
    def from_file(path: FilePath) -> SignedPublicKey: ...
    @staticmethod
    def from_file_many(path: FilePath) -> List[SignedPublicKey]: ...
    @staticmethod
    def from_armor_file(path: FilePath) -> Tuple[SignedPublicKey, Headers]: ...
    @staticmethod
    def from_armor_file_many(path: FilePath) -> Tuple[List[SignedPublicKey], Headers]: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def created_at(self) -> int: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def public_params(self) -> PublicParams: ...
    @property
    def packet_version(self) -> PacketHeaderVersion: ...
    @property
    def public_subkey_count(self) -> int: ...
    @property
    def primary_key(self) -> PublicKey: ...
    @property
    def details(self) -> SignedKeyDetails: ...
    @property
    def public_subkeys(self) -> List[SignedPublicSubKey]: ...
    @property
    def user_ids(self) -> List[str]: ...
    def verify_bindings(self) -> None: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...

class SignedSecretKey:
    @staticmethod
    def from_armor(data: str) -> Tuple[SignedSecretKey, Headers]: ...
    @staticmethod
    def from_armor_many(data: str) -> Tuple[List[SignedSecretKey], Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> SignedSecretKey: ...
    @staticmethod
    def from_bytes_many(data: bytes) -> List[SignedSecretKey]: ...
    @staticmethod
    def from_file(path: FilePath) -> SignedSecretKey: ...
    @staticmethod
    def from_file_many(path: FilePath) -> List[SignedSecretKey]: ...
    @staticmethod
    def from_armor_file(path: FilePath) -> Tuple[SignedSecretKey, Headers]: ...
    @staticmethod
    def from_armor_file_many(path: FilePath) -> Tuple[List[SignedSecretKey], Headers]: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def created_at(self) -> int: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def public_params(self) -> PublicParams: ...
    @property
    def packet_version(self) -> PacketHeaderVersion: ...
    @property
    def public_subkey_count(self) -> int: ...
    @property
    def primary_key(self) -> SecretKey: ...
    @property
    def details(self) -> SignedKeyDetails: ...
    @property
    def public_subkeys(self) -> List[SignedPublicSubKey]: ...
    @property
    def secret_subkey_count(self) -> int: ...
    @property
    def secret_subkeys(self) -> List[SignedSecretSubKey]: ...
    @property
    def user_ids(self) -> List[str]: ...
    def primary_secret_s2k(self) -> S2kParams: ...
    def secret_subkey_s2ks(self) -> List[S2kParams]: ...
    def verify_bindings(self) -> None: ...
    def to_public_key(self) -> SignedPublicKey: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...

class KeyFlags:
    @property
    def certify(self) -> bool: ...
    @property
    def sign(self) -> bool: ...
    @property
    def encrypt_communications(self) -> bool: ...
    @property
    def encrypt_storage(self) -> bool: ...
    @property
    def authenticate(self) -> bool: ...
    @property
    def shared(self) -> bool: ...
    @property
    def draft_decrypt_forwarded(self) -> bool: ...
    @property
    def group(self) -> bool: ...
    @property
    def adsk(self) -> bool: ...
    @property
    def timestamping(self) -> bool: ...

class Features:
    @property
    def seipd_v1(self) -> bool: ...
    @property
    def seipd_v2(self) -> bool: ...

class Notation:
    @property
    def human_readable(self) -> bool: ...
    @property
    def name(self) -> bytes: ...
    @property
    def value(self) -> bytes: ...

class RevocationKey:
    @property
    def class_id(self) -> int: ...
    @property
    def class_name(self) -> Literal["default", "sensitive"]: ...
    @property
    def public_key_algorithm(self) -> PublicKeyAlgorithmName: ...
    @property
    def fingerprint(self) -> bytes: ...

class PublicKeyEncryptedSessionKey:
    @property
    def version(self) -> int: ...
    @property
    def public_key_algorithm(self) -> Optional[PublicKeyAlgorithmName]: ...
    @property
    def recipient_key_id(self) -> Optional[str]: ...
    @property
    def recipient_fingerprint(self) -> Optional[str]: ...
    @property
    def recipient_is_anonymous(self) -> bool: ...
    def values_bytes(self) -> Optional[bytes]: ...
    def to_bytes(self) -> bytes: ...

class SymKeyEncryptedSessionKey:
    @property
    def version(self) -> int: ...
    @property
    def symmetric_algorithm(self) -> Optional[SymmetricAlgorithmName]: ...
    @property
    def aead_algorithm(self) -> Optional[AeadAlgorithmName]: ...
    @property
    def string_to_key(self) -> Optional[StringToKey]: ...
    @property
    def encrypted_key(self) -> Optional[bytes]: ...
    @property
    def aead_iv(self) -> Optional[bytes]: ...
    @property
    def is_supported(self) -> bool: ...
    def to_bytes(self) -> bytes: ...

class EncryptedDataPacket:
    @property
    def kind(self) -> Literal["sed", "seipd-v1", "seipd-v2", "gnupg-aead"]: ...
    @property
    def version(self) -> Optional[int]: ...
    @property
    def symmetric_algorithm(self) -> Optional[SymmetricAlgorithmName]: ...
    @property
    def aead_algorithm(self) -> Optional[AeadAlgorithmName]: ...
    @property
    def chunk_size(self) -> Optional[int]: ...
    @property
    def salt(self) -> Optional[bytes]: ...
    @property
    def iv(self) -> Optional[bytes]: ...
    def data(self) -> bytes: ...
    def to_bytes(self) -> bytes: ...

class SymEncryptedData(EncryptedDataPacket): ...
class SymEncryptedProtectedData(EncryptedDataPacket): ...
class GnupgAeadData(EncryptedDataPacket): ...

class MessageBuilder:
    @staticmethod
    def from_bytes(name: str, data: bytes) -> MessageBuilder: ...
    @staticmethod
    def from_file(path: FilePath) -> MessageBuilder: ...
    @staticmethod
    def from_reader(file_name: str, reader: BinaryIO) -> MessageBuilder: ...
    def compression(self, compression: CompressionAlgorithmName) -> MessageBuilder: ...
    def data_mode(self, mode: LiteralDataModeName) -> MessageBuilder: ...
    def sign_binary(self) -> MessageBuilder: ...
    def sign_text(self) -> MessageBuilder: ...
    def partial_chunk_size(self, size: int) -> MessageBuilder: ...
    def seipd_v1(
        self, symmetric_algorithm: SymmetricAlgorithmName
    ) -> MessageBuilder: ...
    def seipd_v2(
        self,
        symmetric_algorithm: SymmetricAlgorithmName,
        aead_algorithm: AeadAlgorithmName,
        chunk_size: Optional[int] = None,
    ) -> MessageBuilder: ...
    def set_session_key(self, session_key: bytes) -> MessageBuilder: ...
    def sign(
        self,
        key: SigningKey,
        password: Optional[str] = None,
        hash_algorithm: HashAlgorithmName = "sha256",
    ) -> MessageBuilder: ...
    def encrypt_to_key(self, key: EncryptionRecipient) -> MessageBuilder: ...
    def encrypt_to_key_anonymous(self, key: EncryptionRecipient) -> MessageBuilder: ...
    def encrypt_with_password(
        self, string_to_key: StringToKey, password: str
    ) -> MessageBuilder: ...
    def session_key(self) -> bytes: ...
    def to_vec(self) -> bytes: ...
    def to_writer(self, writer: BinaryIO) -> None: ...
    def to_armored_string(self, opts: Optional[ArmorOptions] = None) -> str: ...
    def to_armored_writer(
        self, writer: TextIO, opts: Optional[ArmorOptions] = None
    ) -> None: ...
    def to_file(self, path: FilePath) -> None: ...
    def to_armored_file(
        self, path: FilePath, opts: Optional[ArmorOptions] = None
    ) -> None: ...

class LiteralDataHeader:
    @property
    def mode(self) -> LiteralDataModeName: ...
    @property
    def file_name(self) -> bytes: ...
    @property
    def created(self) -> int: ...

class Message:
    @staticmethod
    def from_armor(data: str) -> Tuple[Message, Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> Message: ...
    @staticmethod
    def from_file(path: FilePath) -> Message: ...
    @staticmethod
    def from_armor_file(path: FilePath) -> Tuple[Message, Headers]: ...
    def to_bytes(self) -> bytes: ...
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def headers(self) -> Optional[Headers]: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def is_compressed(self) -> bool: ...
    @property
    def is_literal(self) -> bool: ...
    def as_data_vec(self) -> bytes: ...
    def as_data_string(self) -> str: ...
    def literal_data_header(self) -> Optional[LiteralDataHeader]: ...
    def literal_mode(self) -> Optional[str]: ...
    def literal_filename(self) -> Optional[bytes]: ...
    def signature_count(self) -> int: ...
    def one_pass_signature_count(self) -> int: ...
    def regular_signature_count(self) -> int: ...
    def signatures(self) -> List[Signature]: ...
    def public_key_encrypted_session_key_packets(
        self,
    ) -> List[PublicKeyEncryptedSessionKey]: ...
    def symmetric_key_encrypted_session_key_packets(
        self,
    ) -> List[SymKeyEncryptedSessionKey]: ...
    def encrypted_data_packet(self) -> EncryptedDataPacket: ...
    def verify_signature(self, key: SignedPublicKey, index: int = 0) -> Signature: ...
    def verify(self, key: SignedPublicKey, index: int = 0) -> Signature: ...
    def decrypt(
        self, password: Optional[str], key: SignedSecretKey
    ) -> DecryptedMessage: ...
    def decrypt_with_password(self, password: str) -> DecryptedMessage: ...
    def decrypt_with_session_key(
        self,
        session_key: bytes,
        symmetric_algorithm: Optional[SymmetricAlgorithmName] = None,
    ) -> DecryptedMessage: ...

class LiteralMessage(Message): ...
class CompressedMessage(Message): ...
class SignedMessage(Message): ...

class EncryptedMessage(Message):
    @property
    def esk(
        self,
    ) -> List[Union[PublicKeyEncryptedSessionKey, SymKeyEncryptedSessionKey]]: ...
    @property
    def edata(self) -> EncryptedDataPacket: ...

class DecryptedMessage:
    @property
    def kind(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def is_compressed(self) -> bool: ...
    @property
    def is_literal(self) -> bool: ...
    def as_data_vec(self) -> bytes: ...
    def as_data_string(self) -> str: ...
    def literal_mode(self) -> Optional[str]: ...
    def literal_filename(self) -> Optional[bytes]: ...
    def signature_count(self) -> int: ...
    def one_pass_signature_count(self) -> int: ...
    def regular_signature_count(self) -> int: ...
    def signatures(self) -> List[Signature]: ...
    def verify_signature(self, key: SignedPublicKey, index: int = 0) -> Signature: ...
    def verify(self, key: SignedPublicKey, index: int = 0) -> Signature: ...

class DecryptedLiteralMessage(DecryptedMessage): ...
class DecryptedCompressedMessage(DecryptedMessage): ...
class DecryptedSignedMessage(DecryptedMessage): ...

class DetachedSignature:
    @staticmethod
    def from_armor(data: str) -> Tuple[DetachedSignature, Headers]: ...
    @staticmethod
    def from_armor_many(data: str) -> Tuple[List[DetachedSignature], Headers]: ...
    @staticmethod
    def from_bytes(data: bytes) -> DetachedSignature: ...
    @staticmethod
    def from_bytes_many(data: bytes) -> List[DetachedSignature]: ...
    @staticmethod
    def from_file(path: FilePath) -> DetachedSignature: ...
    @staticmethod
    def from_file_many(path: FilePath) -> List[DetachedSignature]: ...
    @staticmethod
    def from_armor_file(path: FilePath) -> Tuple[DetachedSignature, Headers]: ...
    @staticmethod
    def from_armor_file_many(path: FilePath) -> Tuple[List[DetachedSignature], Headers]: ...
    @staticmethod
    def sign_binary_data(
        rng: CryptoRng,
        key: SigningKey,
        password: Optional[str],
        hash_algorithm: HashAlgorithmName,
        data: bytes,
    ) -> DetachedSignature: ...
    @staticmethod
    def sign_text_data(
        rng: CryptoRng,
        key: SigningKey,
        password: Optional[str],
        hash_algorithm: HashAlgorithmName,
        data: bytes,
    ) -> DetachedSignature: ...
    @property
    def signature(self) -> Signature: ...
    def verify(self, key: SignedPublicKey, data: bytes) -> None: ...
    def verify_file(self, key: SignedPublicKey, path: FilePath) -> None: ...
    def verify_file_signature(self, key: SignedPublicKey, path: FilePath) -> Signature: ...
    def verify_signature(self, key: SignedPublicKey, data: bytes) -> Signature: ...
    def verify_text(self, key: SignedPublicKey, text: str) -> None: ...
    def verify_text_signature(self, key: SignedPublicKey, text: str) -> Signature: ...
    def to_bytes(self) -> bytes: ...
    def to_armored(self) -> str: ...

class CleartextSignedMessage:
    @staticmethod
    def from_armor(data: str) -> Tuple[CleartextSignedMessage, Headers]: ...
    @staticmethod
    def sign(
        text: str,
        key: SigningKey,
        password: Optional[str] = None,
        hash_algorithm: HashAlgorithmName = "sha256",
    ) -> CleartextSignedMessage: ...
    @property
    def text(self) -> str: ...
    def signed_text(self) -> str: ...
    def signature_count(self) -> int: ...
    def signatures(self) -> List[Signature]: ...
    def verify_signature(
        self, key: SignedPublicKey, index: Optional[int] = None
    ) -> Signature: ...
    def verify(
        self, key: SignedPublicKey, index: Optional[int] = None
    ) -> Signature: ...
    def to_armored(self) -> str: ...

def sign_message(
    data: bytes,
    signer: SigningKey,
    password: Optional[str] = None,
    file_name: str = "",
    hash_algorithm: HashAlgorithmName = "sha256",
) -> str: ...
def sign_message_many(
    data: bytes,
    signers: List[SigningKey],
    passwords: Optional[List[Optional[str]]] = None,
    file_name: str = "",
    hash_algorithm: HashAlgorithmName = "sha256",
) -> str: ...
def sign_cleartext_message(
    text: str,
    signer: SigningKey,
    password: Optional[str] = None,
    hash_algorithm: HashAlgorithmName = "sha256",
) -> str: ...
def sign_cleartext_message_many(
    text: str,
    signers: List[SigningKey],
    passwords: Optional[List[Optional[str]]] = None,
    hash_algorithm: HashAlgorithmName = "sha256",
) -> str: ...
def encrypt_session_key_to_recipient(
    session_key: bytes,
    recipient: EncryptionRecipient,
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    anonymous_recipient: bool = False,
) -> PublicKeyEncryptedSessionKey: ...
def encrypt_session_key_with_password(
    session_key: bytes,
    password: str,
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
) -> SymKeyEncryptedSessionKey: ...
def encrypt_message_to_recipient_bytes(
    data: bytes,
    recipient: EncryptionRecipient,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
    anonymous_recipient: bool = False,
) -> bytes: ...
def encrypt_message_to_recipients_bytes(
    data: bytes,
    recipients: List[EncryptionRecipient],
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
    anonymous_recipient: bool = False,
) -> bytes: ...
def encrypt_message_to_recipient(
    data: bytes,
    recipient: EncryptionRecipient,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
    anonymous_recipient: bool = False,
) -> str: ...
def encrypt_message_to_recipients(
    data: bytes,
    recipients: List[EncryptionRecipient],
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
    anonymous_recipient: bool = False,
) -> str: ...
def encrypt_message_with_password_bytes(
    data: bytes,
    password: str,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
) -> bytes: ...
def encrypt_message_with_password(
    data: bytes,
    password: str,
    file_name: str = "",
    version: EncryptionVersionName = "seipd-v2",
    symmetric_algorithm: SymmetricAlgorithmName = "aes256",
    aead_algorithm: AeadAlgorithmName = "ocb",
    compression: Optional[CompressionAlgorithmName] = None,
    session_key: Optional[bytes] = None,
) -> str: ...
