"""rPGP ``pgp::composed`` compatibility namespace."""

from ._openpgp import (
    ArmorOptions,
    CleartextSignedMessage,
    CompressedMessage,
    DecryptedCompressedMessage,
    DecryptedLiteralMessage,
    DecryptedMessage,
    DecryptedSignedMessage,
    DetachedSignature,
    EncryptedMessage,
    EncryptionCaps,
    KeyType,
    LiteralMessage,
    Message,
    MessageBuilder,
    SecretKeyParams,
    SecretKeyParamsBuilder,
    SignedKeyDetails,
    SignedMessage,
    SignedPublicSubKey,
    SignedSecretSubKey,
    SignedUser,
    SignedUserAttribute,
    SubkeyParams,
    SubkeyParamsBuilder,
)
from ._openpgp import PublicKey as SignedPublicKey
from ._openpgp import SecretKey as SignedSecretKey

__all__ = [
    "ArmorOptions",
    "CleartextSignedMessage",
    "CompressedMessage",
    "DecryptedCompressedMessage",
    "DecryptedLiteralMessage",
    "DecryptedMessage",
    "DecryptedSignedMessage",
    "DetachedSignature",
    "EncryptedMessage",
    "EncryptionCaps",
    "KeyType",
    "LiteralMessage",
    "Message",
    "MessageBuilder",
    "SecretKeyParams",
    "SecretKeyParamsBuilder",
    "SignedKeyDetails",
    "SignedMessage",
    "SignedPublicKey",
    "SignedPublicSubKey",
    "SignedSecretKey",
    "SignedSecretSubKey",
    "SignedUser",
    "SignedUserAttribute",
    "SubkeyParams",
    "SubkeyParamsBuilder",
]
