"""rPGP ``pgp::packet`` compatibility namespace."""

from ._openpgp import (
    EncryptedDataPacket,
    Features,
    GnupgAeadData,
    KeyFlags,
    LiteralDataHeader,
    Notation,
    PublicKey,
    PublicKeyEncryptedSessionKey,
    PublicSubkey,
    RevocationKey,
    SecretKey,
    SecretSubkey,
    Signature,
    SymEncryptedData,
    SymEncryptedProtectedData,
    SymKeyEncryptedSessionKey,
    UserAttribute,
)

__all__ = [
    "EncryptedDataPacket",
    "Features",
    "GnupgAeadData",
    "KeyFlags",
    "LiteralDataHeader",
    "Notation",
    "PublicKey",
    "PublicKeyEncryptedSessionKey",
    "PublicSubkey",
    "RevocationKey",
    "SecretKey",
    "SecretSubkey",
    "Signature",
    "SymEncryptedData",
    "SymEncryptedProtectedData",
    "SymKeyEncryptedSessionKey",
    "UserAttribute",
]
